INSERT INTO PARAMETER_MANAGEMENT_SERVICE.ZISWAF_PRODUCT (
        PAYEE_CODE,
        ADDITIONAL_DATA,
        ZISWAF_CATEGORY,
        ZISWAF_NAME,
        ZISWAF_LABEL,
        ZISWAF_PROCESSOR,
        CREDIT_CARD_ALLOWED,
        CURRENT_ALLOWED,
        SAVING_ALLOWED,
        PROVIDER_ID,
        ZISWAF_ACCOUNT,
        IS_DENOM,
        ZISWAF_IMAGE,
        PAYMENT_HANDLER,
        TRANSACTION_CATEGORY,
        TRANSACTION_CODE,
        TRANSACTION_GROUP,
        PRODUCT_NAME_ID,
        PRODUCT_NAME_EN,
        PRODUCT_IMAGE,
        PRODUCT_CONTENT,
        PRODUCT_SHARE_LINK,
        IS_DELETED,
        STATUS,
        CREATED_BY,
        CREATED_DATE,
        MODIFIED_BY,
        MODIFIED_DATE,
        SHARE_LINK,
        ID_AMIL,
        "ORDERING",
        TEST
    )
VALUES(
        'BSI5037',
        NULL,
        35,
        'BSI Maslahat',
        'BSI Maslahat',
        NULL,
        0,
        1,
        1,
        NULL,
        '7026202595',
        0,
        'http://mf8.myinfosys.net:7005/bsi/assets/amilziswaf/BSI%20Maslahat/circle2x.png',
        1,
        'ZISWAF_FITRAH',
        'ALL',
        5,
        'Rp 45.000 per jiwa',
        'Rp 45.000 per jiwa',
        NULL,
        NULL,
        NULL,
        0,
        1,
        'SYSTEM',
        TIMESTAMP '2023-04-27 13:18:30.000000',
        NULL,
        NULL,
        NULL,
        350,
        1,
        NULL
    );