UPDATE PARAMETER_MANAGEMENT_SERVICE.ZISWAF_PRODUCT
SET ZISWAF_IMAGE = 'https://bsisuperapp2.bankbsi.co.id/assets/amilziswaf/Rumah%20Zakat/Amil%20Ziswaf%402x.png'
WHERE TRANSACTION_CATEGORY = 'ZISWAF_FITRAH'
    AND PAYEE_CODE = 'BSI5039';